name: Pre-Check
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: 20
      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
      - name: Install node modules
        run: npm ci
      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
      - uses: nrwl/nx-set-shas@v3
      - run: git branch --track main origin/main
      - name: Build and deploy the preview of affected apps
        run: npx nx affected -t build deploy-preview --parallel=2 --output-style=stream --args="--token=${{ secrets.VERCEL_TOKEN }} --verbose"
      



